version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    image: ${DOCKER_USERNAME}/parasite-cleanse-landing:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN=${NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN}
      - NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN=${NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN}
      - NEXT_PUBLIC_PRODUCT_ID=${NEXT_PUBLIC_PRODUCT_ID}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3 